export const constData =
{
	buttonNext: document.getElementById('button-next'),
	buttonPrev: document.getElementById('button-prev'),
	userList: document.getElementById('user-list'),
	userTemplate: document.getElementById('user-template'),
	currentPage: document.getElementById('cur-page'),
	pageCountTemplate: document.getElementById('page-count-template'),
	pageNumber: document.getElementById('page-number'),
	authorizatedContent: document.getElementById('content-block'),
	loginForm: document.getElementById('login-block'),
	form: document.getElementById('form'),
	emailField: document.getElementById('email'),
	passwordField: document.getElementById('password'),
	lastNameField: document.getElementById('enter-last-name'),
	loginButton: document.getElementById('login-button'),
	newUserList: document.getElementById('new-user-list'),
	newUserTemplate: document.getElementById('new-user-template'),
	messageBlock: document.getElementById('message-block'),
	errorBlock: document.getElementById('error-block'),
	navBlock: document.getElementById('nav-block'),
	editElementContainer: document.getElementById('edit-elem'),
};
