const CONSTANTS = {
	BUTTON_NEXT: document.getElementById('button-next'),
	BUTTON_PREV: document.getElementById('button-prev'),
	USER_LIST: document.getElementById('user-list'),
	USER_TEMPLATE: document.getElementById('user-template'),
	CURRENT_PAGE: document.getElementById('cur-page'),
	PAGE_COUNT: document.getElementById('page-count-template'),
	PAGE_NUMBER: document.getElementById('page-number'),
	AUTHORIZATED_CONTENT: document.getElementById('content-block'),
	LOGIN_FORM: document.getElementById('login-block'),
	FORM: document.getElementById('form'),
	EMAIL_FIELD: document.getElementById('email'),
	PASSWORD_FIELD: document.getElementById('password'),
	LAST_NAME_FIELD: document.getElementById('enter-last-name'),
	BUTTON_LOGIN: document.getElementById('login-button'),
	NEW_USER_LIST: document.getElementById('new-user-list'),
	NEW_USER_TEMPLATE: document.getElementById('new-user-template'),
	MESSAGE_BLOCK: document.getElementById('message-block'),
	ERROR_BLOCK: document.getElementById('error-block'),
	NAV_BLOCK: document.getElementById('nav-block'),
	EDIT_ELEMENT_CONTAINER: document.getElementById('edit-elem'),
}